defaults:
  - training: default
  - trainer: default
  - data: default
  - output: default
  - clip: default
  - hydra: default
  - _self_

seed: 42
patience: 20
resume_checkpoint: None

callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: ${patience}
    mode: min
  val_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: val_loss
    filename: best-val-model-{epoch:03d}-{val_loss:.3f}
    save_top_k: 1
    mode: min
  train_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: train_loss
    filename: best-train-model-{epoch:03d}-{train_loss:.3f}
    save_top_k: 1
    mode: min
  lr_monitor:
    _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: "step"

compile:
  enabled: false
  mode: "default"
