_target_: training.autoencoder_trainer.LightningMultiTaskAutoencoder

defaults:
  - model: default
  - optimizer: adamW
  - lr_scheduler: linear_warmup_cosine

loss_module:
  _target_: training.losses.losses.CameraTrajectoryLoss
  clip_embeddings:
    _target_: data.simulation.init_captions.initialize_all_clip_embeddings
    clip_model_name: ${clip.model_name}
    cache_file: clip_embeddings_${clip.model_name}_cache.pkl

noise:
  initial_std: 0.1
  final_std: 0.05

mask:
  initial_ratio: 0.1
  final_ratio: 0.8

teacher_forcing_schedule:
  initial_ratio: 0.8
  final_ratio: 0.2
